build:
  verbosity: minimal

clone_depth: 30

build_script :
 - '%BASH_PATH% -lc "cd $APPVEYOR_BUILD_FOLDER; ./antlr.sh"'
 - '%BASH_PATH% -lc "cd $APPVEYOR_BUILD_FOLDER; wget https://ci.appveyor.com/api/projects/yanntm/libDDD/artifacts/windows.zip"'
 - '%BASH_PATH% -lc "cd $APPVEYOR_BUILD_FOLDER; 7z e windows.zip"'
 - DIR
 - '%BASH_PATH% -lc "cd $APPVEYOR_BUILD_FOLDER; autoreconf -vfi && ./configure --prefix=$(pwd)/usr/local/ CPPFLAGS=-I$(pwd)/usr/local/include LDFLAGS=-L$(pwd)/usr/local/lib --with-antlrc=$(pwd)/usr/local/ --with-antlrjar=$(pwd)/usr/local/lib/antlr-3.4-complete.jar --enable-nolto --enable-mingw-native && make && make install"'
 - '%BASH_PATH% -lc "cd $APPVEYOR_BUILD_FOLDER; strip -s bin/its-reach.exe"'
 - '%BASH_PATH% -lc "cd $APPVEYOR_BUILD_FOLDER; 7z a -tzip windows.zip usr/ "'
 
 # SHELL=%BASH_PATH%
 
 
environment :
 MSYSTEM: MINGW64 
 BASH_PATH: C:\msys64\usr\bin\bash

 
artifacts:
  - path: bin/its-reach.exe
    name: its-reach.exe
    type: zip

  - path: windows.zip
    name: windows.zip

      